{% set name = "eventkit" %}
{% set version = "0.8.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ea0ee97903d0713ded98aacdba277cea07d01af86c2480210df7802f64e5879e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy

test:
  imports:
    - eventkit

about:
  home: https://github.com/erdewit/eventkit
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Event-driven data pipelines
  description: |
    The primary use cases of eventkit are
      * to send events between loosely coupled components;
      * to compose all kinds of event-driven data pipelines.
    The interface is kept as Pythonic as possible, with familiar names from Python and its libraries where possible. 
    For scheduling asyncio is used and there is seamless integration with it.
  doc_url: https://eventkit.readthedocs.io/en/latest/api.html
  dev_url: https://github.com/erdewit/eventkit

extra:
  recipe-maintainers:
    - yehoshuadimarsky
