travis:
  secure:
    BINSTAR_TOKEN: FUUJ5hD/lyS8rUbF/hC0t9vCxaoPPCbxat1U4lTa/TgQtwUpxdFQIsM4zR4E5LsdVh63KAE07ayRsNZsvSLrcanF65yXB5nYWsDw+dLa/zjTG/0D7PosmZgFqYHUHYZxVzIlahJFrAODEb5SdsFnfwsd2im4nsTuz/KlHc6oGZKjySpa2sAir+V60HODgWQeniWRjnYYqr7/RQgaZPqPrH5R0jg5o9RjqDpE65E2jHmlLJIx5b0ekaOlg1z6Ar6vgiKfOhzbKxmCD3hrjJkR0cgtzSHAaQy0vCj0UBJXDbOdapinuVyWP6uaGcRPjejyV8A2rGd8+Yj2kq555bYM5xmo1K0fi6aX8MqXmPvpH2LlsCe6Pjccn0zUfoOxIs4A7thKyaLSNKBqVpGk/HUy8wJX8hcIRjsrXpSMLCKHhj9Q29J8JwBG35iYWcSRmgQ4Gd3Y7FdxTom6h+ihsl5AtC2KbSgxt2ugowXFKLvlBblNtp9VPK+yaAEBhsKdUwLfGft+NLagjchOznG41HT0J673FGITsDNVfLbS6Wu9iqw3vPSRvy1sDcRmsLvpGNZ+gWPOdQsw5lVePXbLb7S/Vjpy71zdMehhsTZjbUmErUvCkGHRRhQ5ObkMTjJewW2vHLuT+wBf/PzDxyIZLPRZyGb2OLHw/t9O3jxyql1jpqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
